<!--
[공식 사이트]
  https://vuejs.org/api/sfc-script-setup.html#namespaced-components
[예제]
  https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCAqIGFzIEZvcm0gZnJvbSAnLi9mb3JtLWNvbXBvbmVudHMuanMnXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8Rm9ybS5JbnB1dD5cbiAgICA8Rm9ybS5MYWJlbD5sYWJlbDwvRm9ybS5MYWJlbD5cbiAgPC9Gb3JtLklucHV0PlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIixcbiAgICBcInZ1ZS9zZXJ2ZXItcmVuZGVyZXJcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvc2VydmVyLXJlbmRlcmVyLmVzbS1icm93c2VyLmpzXCJcbiAgfVxufSIsImZvcm0tY29tcG9uZW50cy5qcyI6ImV4cG9ydCB7IGRlZmF1bHQgYXMgSW5wdXQgfSBmcm9tICcuL0lucHV0LnZ1ZSdcbmV4cG9ydCB7IGRlZmF1bHQgYXMgTGFiZWwgfSBmcm9tICcuL0xhYmVsLnZ1ZSciLCJJbnB1dC52dWUiOiI8dGVtcGxhdGU+XG4gIDxzbG90Lz5cbiAgPGlucHV0PlxuPC90ZW1wbGF0ZT4iLCJMYWJlbC52dWUiOiI8dGVtcGxhdGU+XG4gIDxsYWJlbD48c2xvdC8+PC9sYWJlbD5cbjwvdGVtcGxhdGU+In0=
-->
<template>
  <Form.Input>
    <Form.Label>label</Form.Label>
  </Form.Input>
</template>

<script setup>
import * as Form from "./form-components";
</script>

<style></style>
